-- SYNTHETIC TRAINING DATABASE - NOT REAL PATIENT INFORMATION
SELECT VERSION() AS mysql_version;
SELECT CURRENT_USER() AS connected_user;
SHOW DATABASES;
USE MirthCareTrainingDB;
SELECT DATABASE() AS current_database;
